language: php

# Install Haxe
before_script:
  - sudo apt-get install python-software-properties -y #for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - mkdir bin

script:
  - haxe -neko bin/TestAll.n -main TestAll -cp test && neko bin/TestAll.n